# Generated by Django 2.1.5 on 2022-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20220322_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.CharField(max_length=128),
        ),
    ]
